name: imgproc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3.0
  - torchvision
  - torchaudio
  - pip:
      - lpips
      - tqdm
      - pillow
      - scikit-image
      - matplotlib
      - opencv-python